In [ ]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

In [ ]:

import random

from gym_lattice.envs import Lattice2DEnv
from gymnasium import spaces
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.policies import ActorCriticPolicy

np.random.seed(42)

# seq = ''.join(random.choices('HP', k=6))
seq = "hhppppphhppphppphp".capitalize()
env = Lattice2DEnv(seq, end_ceneterd=True)
env.action_space

model = PPO("MlpPolicy", env, learning_rate=0.001, gamma=1.0, policy_kwargs={"net_arch": []}, tensorboard_log="logs/fit")

model.learn(total_timesteps=1000000)

for i_episodes in range(1):
    env.reset()
    while not env.done:
        # Random agent samples from action space
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        env.render()
        if terminated or truncated:
            print("Episode finished! Reward: {} | Collisions: {} | Actions: {}".format(reward, info['collisions'], info['actions']))
            break

/Users/oliver/uni/protein/gym-lattice/gym_lattice/envs/lattice2d_env.py:208: UserWarning: WARN: Your agent was trapped! Ending the episode.
  logger.warn('Your agent was trapped! Ending the episode.')


  (Up)
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
******************H******************
******************H******************
*************************************
*************************************
*************************************
*************************************
*************************************
*************************************
*****

In [12]:
env = Lattice2DEnv('HPHPHPH', end_ceneterd=True)
env.step(3)
env.step(3)
env.step(3)
env.step(1)
env.step(1)
grid, _, _, _, _ = env.step(3)
print(grid)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  1 -1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 -1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
